import colors from "color-name";

const NAMES_ZH: Record<string, string> = {
  aliceblue: "爱丽丝蓝",
  antiquewhite: "古董白",
  aqua: "水色",
  aquamarine: "海蓝宝石",
  azure: "蔚蓝",
  beige: "米色",
  bisque: "陶坯黄",
  black: "黑色",
  blanchedalmond: "杏仁白",
  blue: "蓝色",
  blueviolet: "蓝紫色",
  brown: "棕色",
  burlywood: "硬木色",
  cadetblue: "军服蓝",
  chartreuse: "黄绿色",
  chocolate: "巧克力色",
  coral: "珊瑚红",
  cornflowerblue: "矢车菊蓝",
  cornsilk: "玉米丝色",
  crimson: "绯红",
  cyan: "青色",
  darkblue: "深蓝",
  darkcyan: "深青",
  darkgoldenrod: "深金菊",
  darkgray: "深灰",
  darkgreen: "深绿",
  darkgrey: "深灰",
  darkkhaki: "深卡其",
  darkmagenta: "深洋红",
  darkolivegreen: "深橄榄绿",
  darkorange: "深橙",
  darkorchid: "深兰花",
  darkred: "深红",
  darksalmon: "深鲑红",
  darkseagreen: "深海绿",
  darkslateblue: "深石板蓝",
  darkslategray: "深石板灰",
  darkslategrey: "深石板灰",
  darkturquoise: "深松石",
  darkviolet: "深紫罗兰",
  deeppink: "深粉",
  deepskyblue: "深天蓝",
  dimgray: "暗灰",
  dimgrey: "暗灰",
  dodgerblue: "道奇蓝",
  firebrick: "砖红",
  floralwhite: "花卉白",
  forestgreen: "森林绿",
  fuchsia: "品红",
  gainsboro: "庚斯博罗灰",
  ghostwhite: "幽灵白",
  gold: "金色",
  goldenrod: "金菊色",
  gray: "灰色",
  green: "绿色",
  greenyellow: "黄绿色",
  grey: "灰色",
  honeydew: "蜜瓜色",
  hotpink: "艳粉",
  indianred: "印度红",
  indigo: "靛蓝",
  ivory: "象牙色",
  khaki: "卡其",
  lavender: "薰衣草",
  lavenderblush: "薰衣草红",
  lawngreen: "草坪绿",
  lemonchiffon: "柠檬绸",
  lightblue: "浅蓝",
  lightcoral: "浅珊瑚",
  lightcyan: "浅青",
  lightgoldenrodyellow: "浅金菊黄",
  lightgray: "浅灰",
  lightgreen: "浅绿",
  lightgrey: "浅灰",
  lightpink: "浅粉",
  lightsalmon: "浅鲑红",
  lightseagreen: "浅海绿",
  lightskyblue: "浅天蓝",
  lightslategray: "浅石板灰",
  lightslategrey: "浅石板灰",
  lightsteelblue: "浅钢蓝",
  lightyellow: "浅黄",
  lime: "柠檬绿",
  limegreen: "青柠绿",
  linen: "亚麻色",
  magenta: "洋红",
  maroon: "栗色",
  mediumaquamarine: "中海蓝宝石",
  mediumblue: "中蓝",
  mediumorchid: "中兰花",
  mediumpurple: "中紫",
  mediumseagreen: "中海绿",
  mediumslateblue: "中石板蓝",
  mediumspringgreen: "中春绿",
  mediumturquoise: "中松石",
  mediumvioletred: "中紫红",
  midnightblue: "午夜蓝",
  mintcream: "薄荷奶油",
  mistyrose: "雾玫瑰",
  moccasin: "鹿皮色",
  navajowhite: "纳瓦霍白",
  navy: "海军蓝",
  oldlace: "旧蕾丝",
  olive: "橄榄色",
  olivedrab: "橄榄褐",
  orange: "橙色",
  orangered: "橙红色",
  orchid: "兰花紫",
  palegoldenrod: "淡金菊",
  palegreen: "淡绿",
  paleturquoise: "淡松石",
  palevioletred: "淡紫红",
  papayawhip: "番木瓜",
  peachpuff: "桃肉色",
  peru: "秘鲁色",
  pink: "粉色",
  plum: "李子色",
  powderblue: "粉蓝",
  purple: "紫色",
  rebeccapurple: "丽贝卡紫",
  red: "红色",
  rosybrown: "玫瑰棕",
  royalblue: "皇家蓝",
  saddlebrown: "鞍褐",
  salmon: "鲑红",
  sandybrown: "沙棕",
  seagreen: "海绿",
  seashell: "贝壳白",
  sienna: "赭色",
  silver: "银色",
  skyblue: "天蓝",
  slateblue: "石板蓝",
  slategray: "石板灰",
  slategrey: "石板灰",
  snow: "雪白",
  springgreen: "春绿",
  steelblue: "钢蓝色",
  tan: "茶色",
  teal: "青绿",
  thistle: "蓟色",
  tomato: "番茄红",
  turquoise: "松石色",
  violet: "紫罗兰",
  wheat: "小麦色",
  white: "白色",
  whitesmoke: "烟白",
  yellow: "黄色",
  yellowgreen: "黄绿色",
};

export function nearestColorName(r: number, g: number, b: number): { en: string; zh: string } {
  let best = "black";
  let bestDist = Number.POSITIVE_INFINITY;
  for (const [name, rgb] of Object.entries(colors)) {
    if (name.includes("grey")) continue;
    const [cr, cg, cb] = rgb;
    const dist = (r - cr) ** 2 + (g - cg) ** 2 + (b - cb) ** 2;
    if (dist < bestDist) {
      bestDist = dist;
      best = name;
    }
  }
  return {
    en: prettyEn(best),
    zh: NAMES_ZH[best] ?? prettyEn(best),
  };
}

function prettyEn(id: string): string {
  const spaced = id
    .replace(
      /^(dark|light|medium|deep|pale|dim|navajo|rebecca|lawn|lemon|floral|forest|ghost|honey|indian|lavender|midnight|mint|misty|old|olive|orange|papaya|peach|powder|rosy|royal|saddle|sandy|sea|sky|slate|spring|steel|white|yellow|blue|blanched|cadet|cornflower|dodger|green|lime)/,
      "$1 ",
    )
    .replace(
      /(blue|green|red|white|black|gray|grey|violet|orange|purple|pink|brown|yellow|cyan|aqua|navy|teal|olive|maroon|silver|gold|coral|salmon|khaki|turquoise|orchid|indigo|crimson|azure|ivory|beige|rose|slate|sky|mint)$/i,
      " $1",
    )
    .replace(/\s+/g, " ")
    .trim();
  return spaced.replace(/\b\w/g, (ch) => ch.toUpperCase());
}
